// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGQTz4bNbEnMxpmjCnkLZGZyISFbWDL6g',
    appId: '1:449326385640:web:489280cb4f033f16d83c5d',
    messagingSenderId: '449326385640',
    projectId: 'tasknova-4278c',
    authDomain: 'tasknova-4278c.firebaseapp.com',
    storageBucket: 'tasknova-4278c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkEXkOj1GVTH8xin679Let0y4EmnCwNiI',
    appId: '1:449326385640:android:b4b25c0a727e844cd83c5d',
    messagingSenderId: '449326385640',
    projectId: 'tasknova-4278c',
    storageBucket: 'tasknova-4278c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR189n85a5isNz0eBdukgNN2bIgjy7Tq4',
    appId: '1:449326385640:ios:ffb098a46625b540d83c5d',
    messagingSenderId: '449326385640',
    projectId: 'tasknova-4278c',
    storageBucket: 'tasknova-4278c.firebasestorage.app',
    iosBundleId: 'com.example.tasknova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR189n85a5isNz0eBdukgNN2bIgjy7Tq4',
    appId: '1:449326385640:ios:ffb098a46625b540d83c5d',
    messagingSenderId: '449326385640',
    projectId: 'tasknova-4278c',
    storageBucket: 'tasknova-4278c.firebasestorage.app',
    iosBundleId: 'com.example.tasknova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGQTz4bNbEnMxpmjCnkLZGZyISFbWDL6g',
    appId: '1:449326385640:web:8bdf551f9ad138f2d83c5d',
    messagingSenderId: '449326385640',
    projectId: 'tasknova-4278c',
    authDomain: 'tasknova-4278c.firebaseapp.com',
    storageBucket: 'tasknova-4278c.firebasestorage.app',
  );
}